In [2]:
import cv2
import numpy as np

# np.set_printoptions(threshold=np.inf)
def display_im(img): 
    cv2.namedWindow("Image")   # ,cv2.WINDOW_NORMAL
    cv2.imshow("Image", img)   
    cv2.waitKey (0)  
    cv2.destroyAllWindows()  

img = cv2.imread(r'img.png')
display_im(img)

In [6]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# display_im(img_gray)
cv2.imwrite('img_gray.png', img_gray)

True

In [22]:
print(len(img)) #告诉洒家你这个数组一共有几行？
print(len(img[0])) # 第一行有几列？
print(len(img[0][0])) # 第一列有几个元素？
print(len(img[0][0][0]))# 第一个元素里有几个东西？

38
80
3


TypeError: object of type 'numpy.uint8' has no len()

In [25]:
img_cut = img_gray[10:30, 30:40]
cv2.imwrite('img_cut.png', img_cut)
print(img_cut)

[[255 255 255 255 255 250 234 255 255 255]
 [255 255 255 255 255 184 128 223 255 255]
 [255 255 255 255 255 239 147 128 231 255]
 [255 255 255 255 255 255 243 144 223 255]
 [255 255 255 255 255 255 255 250 255 250]
 [255 255 255 255 255 255 255 255 255 250]
 [255 255 255 255 252 221 221 221 240 213]
 [255 255 255 255 246 120 120 120 205 200]
 [255 255 255 255 255 252 252 126 205 255]
 [255 255 255 255 255 255 255 126 205 255]
 [255 255 255 255 255 255 255 126 205 255]
 [255 255 255 255 255 255 255 126 205 255]
 [255 255 255 255 255 255 255 126 205 208]
 [255 255 255 255 255 255 253 125 186 242]
 [255 255 255 255 252 200 140 174 166 128]
 [255 255 255 255 255 172 179 254 255 226]
 [255 255 255 255 255 248 254 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]


In [48]:
target = cv2.imread('target.png')
target_grey = cv2.cvtColor(target, cv2.COLOR_BGR2GRAY)

res = cv2.matchTemplate(target_grey, img_gray, cv2.TM_CCOEFF_NORMED)
loc = np.where(res >= res.max())
for pt in zip(*loc[::-1]):
    cv2.rectangle(target, pt, (pt[0] + 80, pt[1] + 38), (7,249,151), 2)
# display_im(target)
print(res)
print(res.max())
print(loc)


[[ 0.13394655  0.1270888   0.10907385 ...,  0.13258654  0.14497454
   0.15154529]
 [ 0.14247611  0.14093842  0.13738178 ...,  0.12257441  0.136502
   0.14708124]
 [ 0.11726408  0.11738922  0.11925564 ...,  0.1119022   0.12650129
   0.13966927]
 ..., 
 [-0.11079745 -0.11103781 -0.11126061 ..., -0.17459854 -0.17728637
  -0.17887017]
 [-0.11440915 -0.11443781 -0.1144247  ..., -0.18694539 -0.18942998
  -0.19084181]
 [-0.11870285 -0.11869675 -0.11863921 ..., -0.19886269 -0.20118494
  -0.20253794]]
0.402108
(array([203], dtype=int64), array([528], dtype=int64))
